# Copyright (c) 2026 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable pointing device subsystem
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Enable SPI & Zephyr input subsystem
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_PINNACLE=y

# Adjust input thread stack size for split peripheral
CONFIG_INPUT_THREAD_STACK_SIZE=1024
